<?php

namespace Database\Seeders;

use App\Models\VipPackage;
use Illuminate\Database\Seeder;

class VipPackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $packages = [
            [
                'name' => 'Đồng',
                'name_en' => 'Bronze',
                'level' => 1,
                'price' => 100000,
                'duration_days' => 30,
                'color' => '#CD7F32',
                'benefits' => [
                    'special_badge' => true,
                    'exclusive_stickers' => 5,
                    'create_rooms' => 2,
                    'ad_free' => true,
                    'chat_priority' => false,
                ],
                'badge_image' => '/assets/vip/bronze-badge.png',
                'frame_image' => '/assets/vip/bronze-frame.png',
                'entrance_animation' => 'bronze_entrance',
                'is_active' => true,
            ],
            [
                'name' => 'Bạc',
                'name_en' => 'Silver',
                'level' => 2,
                'price' => 200000,
                'duration_days' => 30,
                'color' => '#C0C0C0',
                'benefits' => [
                    'special_badge' => true,
                    'exclusive_stickers' => 10,
                    'create_rooms' => 3,
                    'ad_free' => true,
                    'mass_message' => 50,
                    'custom_theme' => true,
                    'chat_priority' => true,
                ],
                'badge_image' => '/assets/vip/silver-badge.png',
                'frame_image' => '/assets/vip/silver-frame.png',
                'entrance_animation' => 'silver_entrance',
                'is_active' => true,
            ],
            [
                'name' => 'Vàng',
                'name_en' => 'Gold',
                'level' => 3,
                'price' => 500000,
                'duration_days' => 30,
                'color' => '#FFD700',
                'benefits' => [
                    'special_badge' => true,
                    'badge_animation' => true,
                    'exclusive_stickers' => 20,
                    'create_rooms' => 5,
                    'ad_free' => true,
                    'mass_message' => 100,
                    'custom_theme' => true,
                    'hide_online_status' => true,
                    'view_profile_visitors' => true,
                    'chat_priority' => true,
                ],
                'badge_image' => '/assets/vip/gold-badge.png',
                'frame_image' => '/assets/vip/gold-frame.png',
                'entrance_animation' => 'gold_entrance',
                'is_active' => true,
            ],
            [
                'name' => 'Bạch Kim',
                'name_en' => 'Platinum',
                'level' => 4,
                'price' => 1000000,
                'duration_days' => 30,
                'color' => '#E5E4E2',
                'benefits' => [
                    'special_badge' => true,
                    'badge_animation' => true,
                    'platinum_frame' => true,
                    'entrance_effect' => true,
                    'exclusive_stickers' => 30,
                    'create_rooms' => 'unlimited',
                    'ad_free' => true,
                    'mass_message' => 'unlimited',
                    'custom_theme' => true,
                    'hide_online_status' => true,
                    'view_profile_visitors' => true,
                    'anonymous_view' => true,
                    'priority_search' => true,
                    'chat_priority' => true,
                ],
                'badge_image' => '/assets/vip/platinum-badge.png',
                'frame_image' => '/assets/vip/platinum-frame.png',
                'entrance_animation' => 'platinum_entrance',
                'is_active' => true,
            ],
            [
                'name' => 'Kim Cương',
                'name_en' => 'Diamond',
                'level' => 5,
                'price' => 2000000,
                'duration_days' => 30,
                'color' => '#B9F2FF',
                'benefits' => [
                    'special_badge' => true,
                    'badge_animation' => true,
                    'diamond_frame' => true,
                    'particle_effects' => true,
                    'entrance_effect' => 'special',
                    'exclusive_stickers' => 50,
                    'create_rooms' => 'unlimited',
                    'ad_free' => true,
                    'mass_message' => 'unlimited',
                    'custom_theme' => true,
                    'hide_online_status' => true,
                    'view_profile_visitors' => true,
                    'anonymous_view' => true,
                    'priority_search' => true,
                    'super_like' => 10,
                    'rewind_swipes' => true,
                    'profile_boost' => true,
                    'chat_priority' => true,
                ],
                'badge_image' => '/assets/vip/diamond-badge.png',
                'frame_image' => '/assets/vip/diamond-frame.png',
                'entrance_animation' => 'diamond_entrance',
                'is_active' => true,
            ],
            [
                'name' => 'Nhà Vua',
                'name_en' => 'King',
                'level' => 6,
                'price' => 5000000,
                'duration_days' => 30,
                'color' => '#FFD700',
                'benefits' => [
                    'special_badge' => true,
                    'crown_icon' => true,
                    'badge_animation' => true,
                    'king_frame' => true,
                    'particle_effects' => true,
                    'entrance_effect' => 'luxury_car',
                    'exclusive_stickers' => 100,
                    'create_rooms' => 'unlimited',
                    'ad_free' => true,
                    'mass_message' => 'unlimited',
                    'custom_theme' => true,
                    'hide_online_status' => true,
                    'view_profile_visitors' => true,
                    'anonymous_view' => true,
                    'priority_search' => true,
                    'super_like' => 'unlimited',
                    'rewind_swipes' => true,
                    'profile_boost' => true,
                    'vip_rooms_access' => true,
                    'personal_assistant' => false,
                    'chat_priority' => true,
                ],
                'badge_image' => '/assets/vip/king-badge.png',
                'frame_image' => '/assets/vip/king-frame.png',
                'entrance_animation' => 'king_entrance',
                'is_active' => true,
            ],
            [
                'name' => 'Hoàng Đế',
                'name_en' => 'Emperor',
                'level' => 7,
                'price' => 10000000,
                'duration_days' => 30,
                'color' => '#FF6B00',
                'benefits' => [
                    'special_badge' => true,
                    'emperor_crown' => true,
                    'golden_aura' => true,
                    'badge_animation' => true,
                    'emperor_frame' => true,
                    'particle_effects' => true,
                    'entrance_effect' => 'dragon',
                    'exclusive_stickers' => 200,
                    'create_rooms' => 'unlimited',
                    'ad_free' => true,
                    'mass_message' => 'unlimited',
                    'custom_theme' => true,
                    'custom_badge_design' => true,
                    'hide_online_status' => true,
                    'view_profile_visitors' => true,
                    'anonymous_view' => true,
                    'priority_search' => true,
                    'super_like' => 'unlimited',
                    'rewind_swipes' => true,
                    'profile_boost' => true,
                    'vip_rooms_access' => true,
                    'personal_assistant' => true,
                    'priority_support' => '24/7',
                    'god_mode' => true,
                    'chat_priority' => true,
                ],
                'badge_image' => '/assets/vip/emperor-badge.png',
                'frame_image' => '/assets/vip/emperor-frame.png',
                'entrance_animation' => 'emperor_entrance',
                'is_active' => true,
            ],
        ];

        foreach ($packages as $package) {
            VipPackage::create($package);
        }

        $this->command->info('✓ Created 7 VIP packages (Bronze → Emperor)');
    }
}
